FROM node:lts
# Set the working directory to /api
WORKDIR /api

# COPY rootCA.pem /usr/local/share/ca-certificates/rootCA.pem
# RUN chmod 644 /usr/local/share/ca-certificates/rootCA.pem && update-ca-certificates

